# Generated by Django 3.2.4 on 2021-06-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientrequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientrequest.brandauto')),
            ],
        ),
    ]
