# Generated by Django 3.2.4 on 2021-06-21 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientrequest', '0002_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='brandauto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientrequest.brandauto'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='modelauto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientrequest.modelauto'),
        ),
    ]
