# Generated by Django 3.2.4 on 2021-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientrequest', '0003_auto_20210621_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandauto',
            name='brand_auto',
            field=models.CharField(max_length=50, verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_name',
            field=models.CharField(max_length=30, verbose_name='Bаше имя'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_phone',
            field=models.CharField(max_length=13, verbose_name='Ваш телефон'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_request',
            field=models.TextField(verbose_name='Список запчастей'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='year_auto',
            field=models.CharField(max_length=4, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='modelauto',
            name='model_auto',
            field=models.CharField(max_length=50, verbose_name='Модель авто'),
        ),
    ]
