# Generated by Django 3.2.4 on 2021-06-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientrequest', '0004_auto_20210624_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandauto',
            name='brand_auto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_request',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='year_auto',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='modelauto',
            name='model_auto',
            field=models.CharField(max_length=50),
        ),
    ]
