# Generated by Django 3.2.4 on 2021-06-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientrequest', '0005_auto_20210624_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='brandauto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientrequest.brandauto', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='client_request',
            field=models.TextField(verbose_name='Запчасти'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='modelauto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientrequest.modelauto', verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='year_auto',
            field=models.CharField(max_length=4, verbose_name='Год выпуска автомобиля'),
        ),
    ]
