# Generated by Django 3.2.5 on 2021-07-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoprequest', '0004_auto_20210704_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=9)),
                ('subscribe', models.BooleanField(null=True)),
                ('shopname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shoprequest.shoprequest')),
            ],
        ),
    ]
