# Generated by Django 3.2.4 on 2021-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoprequest', '0002_shoprequest_shopnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprequest',
            name='shopnumber',
            field=models.CharField(max_length=13),
        ),
    ]
